### ISSUE TITLE
Make "tags.html" its own resource and access it from both product/#/show and product/#/edit

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/OpenFn-Site#250]

**Comment by Jasonbhaas** [comment]
Using ng-include, it is simple to move the overlapping code from show and edit pages and into a separate page, called tags.html, that is accessible to both. However, the scope of product controller on the show and edit page does not extend to tags.html, so there must be a seperate ng-controller=Products Controller in tags.html. This causes issues with the submit button, in particular on the edit page. There is one button at the bottom of the page which submits all changes (description, costs, ect. and Tags). The problem is, because the scope of products controller doesn't extend to the tags.html page, the edits to the tags are not included with the edits to description, cost ect. Fixing this would require a separate submit button for tags, and creates more problems than it solves.
